# Generated by Django 5.2.7 on 2025-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
    ]
