# Generated by Django 5.2.7 on 2025-11-17 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_coupon_address_paymentmethod_paymentorder_and_more'),
        ('users', '0002_alter_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.user'),
        ),
    ]
